### PR TITLE
add keyword extraction

### PR DESCRIPTION
**Pull request by BrendaHijmans**
#### Checklist
- [x] Clean commits
- [x] Placed in projectmap
- Tested CSS (if applicable)

### CODE REVIEW

**Review by connoratrug — COMMENTED** [review]
Looks good to me , maybe we should remove the output from the github repo and add a readme doc on how to run the script.

**Comment by sidohaakma** [comment]
[Migrate data from LifeCycle to EMX2 model](https://trello.com/c/7izxgCgw/5-migrate-data-from-lifecycle-to-emx2-model)

**Comment by BrendaHijmans** [comment]
> Looks good to me , maybe we should remove the output from the github repo and add a readme doc on how to run the script.

okay, i will add a readme.
and is it a good idea to add the files in the output folder to a .gitignore then?

**Comment by connoratrug** [comment]
> and is it a good idea to add the files in the output folder to a .gitignore then?

i would think so, but maybe we should discuss, for small data set is that is infrequently generated adding the output may be be a good thing , i'm not really sure. as long as we have a clear up to date readme on how to use this it will be oke i think

**Review by sidohaakma — APPROVED** [review]

**Pull request merged**
